mindmap
  root((MECANISMOS de PROTEÇÃO CONSTITUCIONAL))
    1 - CONTROLE DE CONSTITUCIONALIDADE
    2 - REMÉDIOS CONSTITUCIONAIS
    4 - FUNÇÃO DO MINISTÉRIO PÚBLICO
    3 - INTERVENÇÃO FEDERAL E INTERVENÇÃO ESTADUAL
    5 - GARANTIAS INSTITUCIONAIS
    6 - DEFESA DO ESTADO E DAS INSTITUIÇÕES DEMOCRÁTICAS